inherit_gem:
  rubocop-shopify: rubocop.yml

require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  Exclude:
    - "db/**/*"
    - "bin/**/*"
    - "vendor/**/*"
    - "node_modules/**/*"

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 10

Metrics/ClassLength:
  Max: 100
